

services:
  proxy:
    image: self-control-proxy:latest
    container_name: self-control-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.self-control.rule=Host(`yt.sonbn.xyz`)"
      - "traefik.http.routers.self-control.entrypoints=websecure"
      - "traefik.http.routers.self-control.tls.certresolver=le"
      - "traefik.http.services.self-control.loadbalancer.server.port=8080"
      - "traefik.http.routers.self-control.priority=20"
    environment:
      - PROXY_PORT=8080
    expose:
      - "8080"
    networks:
      - self-control
    
networks:
  self-control:
    driver: bridge
    proxy_network:
    name: ${TRAEFIK_NETWORK}
    external: true
  sunflower_data:
    name: ${DATA_NETWORK}
    external: true
